version: "3.2"

x-kafka: &kafka_template
  volumes:
    - ./assets/jmx-exporter:/usr/share/jmx-exporter
  environment: &kafka_environment
    EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.16.1.jar=1234:/usr/share/jmx-exporter/kafka_broker.yml

services:
  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./assets/prometheus/prometheus-config/:/etc/prometheus

  grafana:
    image: grafana/grafana:8.1.3
    container_name: grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - 3000:3000
    volumes:
      - ./assets/grafana/provisioning/:/etc/grafana/provisioning
